name: Docker Image CI/CD - Notification Center

env:
  DOCKER_IMAGE: notification-center

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-config-inline: |
          [registry."ghcr.io"]
            mirrors = ["ghcr.io"]

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build and Push Image with Cache
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:      
      - name: SSH into VM and Deploy new Image with Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username:  ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Fail script on first error
            set -e 
            # Login to GitHub Container Registry
            echo "${{ secrets.CI_ORG_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Deploy new Image
            cd /root/modapto/notification-center
            docker compose pull ${{ env.DOCKER_IMAGE }}
            docker compose up -d --no-deps ${{ env.DOCKER_IMAGE }}

            # Loggout
            docker logout ghcr.io
